// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	service "github.com/nghiem-pham/bookmark-management/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// HealthService is an autogenerated mock type for the HealthService type
type HealthService struct {
	mock.Mock
}

// HealthCheck provides a mock function with no fields
func (_m *HealthService) HealthCheck() *service.HealthCheckResponse {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 *service.HealthCheckResponse
	if rf, ok := ret.Get(0).(func() *service.HealthCheckResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.HealthCheckResponse)
		}
	}

	return r0
}

// NewHealthService creates a new instance of HealthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthService {
	mock := &HealthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
